version: "3.7"

services:
  sdn:
    image: sdn
    restart: unless-stopped
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db_sdn
    env_file:
      - .env

  db_sdn:
    image: postgres:14.10-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgresql/db_sdn/data:/var/lib/postgresql/data
