// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sdn_queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SdnList struct {
	ID        int32            `json:"id"`
	Uid       int64            `json:"uid"`
	FirstName pgtype.Text      `json:"first_name"`
	LastName  pgtype.Text      `json:"last_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
