// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sdn_queries

import (
	"context"
)

type Querier interface {
	DeleteOrder(ctx context.Context, id int32) error
	GetSdnById(ctx context.Context, id int32) (SdnList, error)
	GetSdnByUid(ctx context.Context, uid int64) ([]SdnList, error)
	GetSdnByUidAndName(ctx context.Context, arg GetSdnByUidAndNameParams) (SdnList, error)
	InsertSdn(ctx context.Context, arg InsertSdnParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
