// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package upload_attempts_queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SdnUploadAttempt struct {
	ID          int32            `json:"id"`
	Status      int16            `json:"status"`
	PublishDate pgtype.Timestamp `json:"publish_date"`
	StartedAt   pgtype.Timestamp `json:"started_at"`
}
